version: '3.8'
name: pickleball
services:
  mysql:
    container_name: pickleball-mariadb
    image: mariadb:10.11
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './.temp/mysql:/var/lib/mysql'
    user: "1000:1000"


# -- migrate error
# docker exec -it pickleball-mariadb mysql -u root -proot
# GRANT CREATE DATABASE ON *.* TO 'user'@'%';
# -- O GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
# GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
# FLUSH PRIVILEGES;
# EXIT; -- Para salir del cliente MySQL